# This Azure Pipeline validates and deploys bundle config (ML resource config and more)
# defined under carharrt_dlt/resources/*
# and carharrt_dlt/databricks.yml.
# The bundle is validated (CI) upon making a PR against the main branch.
# Bundle resources defined for staging are deployed when a PR is merged into the main branch.
# Bundle resources defined for prod are deployed when a PR is merged into the release branch.

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - carharrt_dlt/*

variables:
  - name: workingDirectory
    value: carharrt_dlt
  - group: carharrt_dlt variable group

stages:
# Run StagingBundleCD stage after successfully merging into the main branch
- stage: StagingBundleCD
  displayName: 'Staging bundle deployment for carharrt_dlt'
  # Trigger deployment of bundle resources when PRs are merged into the main branch
  condition: |
     and(
        not(eq(variables['Build.Reason'], 'PullRequest')),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
     )

  jobs:
  - job: StagingBundleCD
    displayName: 'Bundle Deployment for carharrt_dlt Staging'

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
      persistCredentials: true
      clean: true

      # Install Databricks CLI
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/v0.221.0/install.sh | sh   
      displayName: 'Install Databricks CLI'          

    # Validate bundle to be deployed to the Staging workspace
    - script: |
        databricks bundle validate -t qa_datasci_db
      workingDirectory: $(workingDirectory)
      displayName: 'Validate bundle for staging'
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)
        

    # Deploy bundle to Staging workspace
    - script: |
        databricks bundle deploy -t qa_datasci_db
      workingDirectory: $(workingDirectory)
      displayName: 'Deploy bundle to staging'
      env:
        ARM_TENANT_ID: $(STAGING_AZURE_SP_TENANT_ID)
        ARM_CLIENT_ID: $(STAGING_AZURE_SP_APPLICATION_ID)
        ARM_CLIENT_SECRET: $(STAGING_AZURE_SP_CLIENT_SECRET)

